<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>465fe913-0dd2-429f-a952-f00863455a65</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Analytics" Version="3.8.1" />
    <PackageReference Include="ClosedXML" Version="0.100.3" />
    <PackageReference Include="itextsharp.xmlworker" Version="5.5.13.3" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.13" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.3.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.11" />
    <PackageReference Include="MySql.Data" Version="8.0.32" />
    <PackageReference Include="MySqlConnector" Version="2.2.5" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.OleDb" Version="7.0.0" />
    <PackageReference Include="xunit.extensibility.core" Version="2.4.2" />
    <PackageReference Include="xunit.extensibility.execution" Version="2.4.2" />
  </ItemGroup>

</Project>
